---
- hosts: windows
  gather_facts: no
  tasks:
    - name: Create new Windows domain in a new forest with specific parameters and reboot if required
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path: C:\Windows\NTDS
        dns_domain_name: harel.local
        domain_mode: WinThreshold
        domain_netbios_name: ANSIBLE
        forest_mode: WinThreshold
        safe_mode_password: Adi@12345
        sysvol_path: C:\Windows\SYSVOL
      register: domain_install

    - name: Reboot host if install requires it
      ansible.windows.win_reboot:
      when: domain_install.reboot_required
